# Generated by Django 4.0 on 2022-10-18 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_name', models.CharField(max_length=20)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.budget')),
            ],
        ),
    ]
